////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2008 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 10.1
//  \   \         Application : xaw2verilog
//  /   /         Filename : xc3s_dcm_90m_28m636.v
// /___/   /\     Timestamp : 04/30/2008 10:38:39
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -st c:\usr\pld\coregen\xc3s_dcm_90m_28m636.xaw c:\usr\pld\coregen\xc3s_dcm_90m_28m636
//Design Name: xc3s_dcm_90m_28m636
//Device: xc3s200-ft256-5
//
// Module xc3s_dcm_90m_28m636
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
// Period Jitter (unit interval) for block DCM_INST = 0.04 UI
// Period Jitter (Peak-to-Peak) for block DCM_INST = 1.28 ns
`timescale 1ns / 1ps

module xc3s_dcm_90m_28m636(CLKIN_IN, 
                           RST_IN, 
                           CLKFX_OUT, 
                           LOCKED_OUT);

    input CLKIN_IN;
    input RST_IN;
   output CLKFX_OUT;
   output LOCKED_OUT;
   
   wire CLKFX_BUF;
   wire GND_BIT;
   
   assign GND_BIT = 0;
   BUFG CLKFX_BUFG_INST (.I(CLKFX_BUF), 
                         .O(CLKFX_OUT));
   DCM DCM_INST (.CLKFB(GND_BIT), 
                 .CLKIN(CLKIN_IN), 
                 .DSSEN(GND_BIT), 
                 .PSCLK(GND_BIT), 
                 .PSEN(GND_BIT), 
                 .PSINCDEC(GND_BIT), 
                 .RST(RST_IN), 
                 .CLKDV(), 
                 .CLKFX(CLKFX_BUF), 
                 .CLKFX180(), 
                 .CLK0(), 
                 .CLK2X(), 
                 .CLK2X180(), 
                 .CLK90(), 
                 .CLK180(), 
                 .CLK270(), 
                 .LOCKED(LOCKED_OUT), 
                 .PSDONE(), 
                 .STATUS());
   defparam DCM_INST.CLK_FEEDBACK = "NONE";
   defparam DCM_INST.CLKDV_DIVIDE = 2.0;
   defparam DCM_INST.CLKFX_DIVIDE = 11;
   defparam DCM_INST.CLKFX_MULTIPLY = 7;
   defparam DCM_INST.CLKIN_DIVIDE_BY_2 = "TRUE";
   defparam DCM_INST.CLKIN_PERIOD = 22.222;
   defparam DCM_INST.CLKOUT_PHASE_SHIFT = "NONE";
   defparam DCM_INST.DESKEW_ADJUST = "SYSTEM_SYNCHRONOUS";
   defparam DCM_INST.DFS_FREQUENCY_MODE = "LOW";
   defparam DCM_INST.DLL_FREQUENCY_MODE = "LOW";
   defparam DCM_INST.DUTY_CYCLE_CORRECTION = "TRUE";
   defparam DCM_INST.FACTORY_JF = 16'h8080;
   defparam DCM_INST.PHASE_SHIFT = 0;
   defparam DCM_INST.STARTUP_WAIT = "FALSE";
endmodule
