// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


//======================

void Vtop::trace(VerilatedVcdC* tfp, int, int) {
    tfp->spTrace()->addInitCb(&traceInit, __VlSymsp);
    traceRegister(tfp->spTrace());
}

void Vtop::traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) {
    // Callback from tracep->open()
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    if (!vlSymsp->_vm_contextp__->calcUnusedSigs()) {
        VL_FATAL_MT(__FILE__, __LINE__, __FILE__,
                        "Turning on wave traces requires Verilated::traceEverOn(true) call before time 0.");
    }
    vlSymsp->__Vm_baseCode = code;
    tracep->module(vlSymsp->name());
    tracep->scopeEscape(' ');
    Vtop::traceInitTop(vlSymsp, tracep);
    tracep->scopeEscape('.');
}

//======================


void Vtop::traceInitTop(void* userp, VerilatedVcd* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceInitSub0(userp, tracep);
    }
}

void Vtop::traceInitSub0(void* userp, VerilatedVcd* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    const int c = vlSymsp->__Vm_baseCode;
    if (false && tracep && c) {}  // Prevent unused
    // Body
    {
        tracep->declBit(c+1,"clk_48", false,-1);
        tracep->declBit(c+2,"clk_12", false,-1);
        tracep->declBus(c+3,"inputs", false,-1, 11,0);
        tracep->declBus(c+4,"VGA_R", false,-1, 7,0);
        tracep->declBus(c+5,"VGA_G", false,-1, 7,0);
        tracep->declBus(c+6,"VGA_B", false,-1, 7,0);
        tracep->declBit(c+7,"VGA_HS", false,-1);
        tracep->declBit(c+8,"VGA_VS", false,-1);
        tracep->declBit(c+9,"VGA_HB", false,-1);
        tracep->declBit(c+10,"VGA_VB", false,-1);
        tracep->declBus(c+11,"AUDIO_L", false,-1, 15,0);
        tracep->declBus(c+12,"AUDIO_R", false,-1, 15,0);
        tracep->declBit(c+13,"ioctl_download", false,-1);
        tracep->declBit(c+14,"ioctl_upload", false,-1);
        tracep->declBit(c+15,"ioctl_wr", false,-1);
        tracep->declBus(c+16,"ioctl_addr", false,-1, 24,0);
        tracep->declBus(c+17,"ioctl_dout", false,-1, 7,0);
        tracep->declBus(c+18,"ioctl_din", false,-1, 7,0);
        tracep->declBus(c+19,"ioctl_index", false,-1, 7,0);
        tracep->declBit(c+20,"ioctl_wait", false,-1);
        tracep->declBit(c+21,"top clk_48", false,-1);
        tracep->declBit(c+22,"top clk_12", false,-1);
        tracep->declBus(c+23,"top inputs", false,-1, 11,0);
        tracep->declBus(c+24,"top VGA_R", false,-1, 7,0);
        tracep->declBus(c+25,"top VGA_G", false,-1, 7,0);
        tracep->declBus(c+26,"top VGA_B", false,-1, 7,0);
        tracep->declBit(c+27,"top VGA_HS", false,-1);
        tracep->declBit(c+28,"top VGA_VS", false,-1);
        tracep->declBit(c+29,"top VGA_HB", false,-1);
        tracep->declBit(c+30,"top VGA_VB", false,-1);
        tracep->declBus(c+31,"top AUDIO_L", false,-1, 15,0);
        tracep->declBus(c+32,"top AUDIO_R", false,-1, 15,0);
        tracep->declBit(c+33,"top ioctl_download", false,-1);
        tracep->declBit(c+34,"top ioctl_upload", false,-1);
        tracep->declBit(c+35,"top ioctl_wr", false,-1);
        tracep->declBus(c+36,"top ioctl_addr", false,-1, 24,0);
        tracep->declBus(c+37,"top ioctl_dout", false,-1, 7,0);
        tracep->declBus(c+38,"top ioctl_din", false,-1, 7,0);
        tracep->declBus(c+39,"top ioctl_index", false,-1, 7,0);
        tracep->declBit(c+40,"top ioctl_wait", false,-1);
        tracep->declBit(c+41,"top pause", false,-1);
        tracep->declBus(c+42,"top audio", false,-1, 7,0);
        tracep->declBus(c+43,"top rgb", false,-1, 8,0);
        tracep->declBus(c+44,"top led", false,-1, 3,0);
        tracep->declBus(c+45,"top trakball", false,-1, 7,0);
        tracep->declBus(c+46,"top joystick", false,-1, 7,0);
        tracep->declBus(c+47,"top playerinput", false,-1, 9,0);
        tracep->declBus(c+48,"top sw1", false,-1, 7,0);
        tracep->declBus(c+49,"top sw2", false,-1, 7,0);
        tracep->declBit(c+50,"top ce_pix", false,-1);
        tracep->declBit(c+51,"top reset", false,-1);
        tracep->declBit(c+52,"top unnamedblk1 old_clk", false,-1);
        tracep->declBit(c+53,"top sharpx1 clk_sys", false,-1);
        tracep->declBit(c+54,"top sharpx1 clk_28636", false,-1);
        tracep->declBit(c+55,"top sharpx1 reset", false,-1);
        tracep->declBit(c+56,"top sharpx1 pal", false,-1);
        tracep->declBit(c+57,"top sharpx1 scandouble", false,-1);
        tracep->declBit(c+58,"top sharpx1 ioctl_download", false,-1);
        tracep->declBus(c+59,"top sharpx1 ioctl_index", false,-1, 7,0);
        tracep->declBit(c+60,"top sharpx1 ioctl_wr", false,-1);
        tracep->declBus(c+61,"top sharpx1 ioctl_addr", false,-1, 24,0);
        tracep->declBus(c+62,"top sharpx1 ioctl_dout", false,-1, 7,0);
        tracep->declBit(c+63,"top sharpx1 ce_pix", false,-1);
        tracep->declBit(c+64,"top sharpx1 HBlank", false,-1);
        tracep->declBit(c+65,"top sharpx1 HSync", false,-1);
        tracep->declBit(c+66,"top sharpx1 VBlank", false,-1);
        tracep->declBit(c+67,"top sharpx1 VSync", false,-1);
        tracep->declBus(c+68,"top sharpx1 video", false,-1, 7,0);
        tracep->declBus(c+69,"top sharpx1 romDo_SharpX1", false,-1, 7,0);
        tracep->declBus(c+70,"top sharpx1 romA", false,-1, 13,0);
        tracep->declBus(c+71,"top sharpx1 ramDi", false,-1, 7,0);
        tracep->declBus(c+72,"top sharpx1 ramDo", false,-1, 7,0);
        tracep->declBus(c+73,"top sharpx1 ramA", false,-1, 15,0);
        tracep->declBit(c+74,"top sharpx1 ramWe", false,-1);
        tracep->declBus(c+75,"top sharpx1 vramDi", false,-1, 7,0);
        tracep->declBus(c+76,"top sharpx1 vramDo", false,-1, 7,0);
        tracep->declBus(c+77,"top sharpx1 vramA", false,-1, 15,0);
        tracep->declBit(c+78,"top sharpx1 vramWe", false,-1);
        tracep->declBus(c+79,"top sharpx1 pcgramDi", false,-1, 7,0);
        tracep->declBus(c+80,"top sharpx1 pcgramDo", false,-1, 7,0);
        tracep->declBus(c+81,"top sharpx1 pcgvramA", false,-1, 15,0);
        tracep->declBit(c+82,"top sharpx1 pcgramWe", false,-1);
        tracep->declBus(c+83,"top sharpx1 gramDi", false,-1, 7,0);
        tracep->declBus(c+84,"top sharpx1 gramDo", false,-1, 7,0);
        tracep->declBus(c+85,"top sharpx1 gramA", false,-1, 15,0);
        tracep->declBit(c+86,"top sharpx1 gramWe", false,-1);
        tracep->declBus(c+87,"top sharpx1 ce", false,-1, 3,0);
        tracep->declBit(c+88,"top sharpx1 pe8M8", false,-1);
        tracep->declBit(c+89,"top sharpx1 ne8M8", false,-1);
        tracep->declBit(c+90,"top sharpx1 pe4M4", false,-1);
        tracep->declBit(c+91,"top sharpx1 ne4M4", false,-1);
        tracep->declBit(c+92,"top sharpx1 pe2M2", false,-1);
        tracep->declBit(c+93,"top sharpx1 ne2M2", false,-1);
        tracep->declBit(c+94,"top sharpx1 pe1M1", false,-1);
        tracep->declBit(c+95,"top sharpx1 ne1M1", false,-1);
        tracep->declBus(c+96,"top sharpx1 di", false,-1, 7,0);
        tracep->declBus(c+97,"top sharpx1 data_out", false,-1, 7,0);
        tracep->declBus(c+98,"top sharpx1 a", false,-1, 15,0);
        tracep->declBit(c+99,"top sharpx1 mreq", false,-1);
        tracep->declBit(c+100,"top sharpx1 iorq", false,-1);
        tracep->declBit(c+101,"top sharpx1 wr", false,-1);
        tracep->declBit(c+102,"top sharpx1 rd", false,-1);
        tracep->declBus(c+103,"top sharpx1 dir", false,-1, 15,0);
        tracep->declBit(c+104,"top sharpx1 dirset", false,-1);
        tracep->declBit(c+105,"top sharpx1 m1", false,-1);
        tracep->declBus(c+458,"top sharpx1 IPL data_width_g", false,-1, 31,0);
        tracep->declBus(c+459,"top sharpx1 IPL addr_width_g", false,-1, 31,0);
        tracep->declBit(c+106,"top sharpx1 IPL clock", false,-1);
        tracep->declBit(c+107,"top sharpx1 IPL ram_cs", false,-1);
        tracep->declBit(c+108,"top sharpx1 IPL wren_a", false,-1);
        tracep->declBus(c+109,"top sharpx1 IPL address_a", false,-1, 12,0);
        tracep->declBus(c+110,"top sharpx1 IPL data_a", false,-1, 7,0);
        tracep->declBus(c+111,"top sharpx1 IPL q_a", false,-1, 7,0);
        tracep->declBit(c+112,"top sharpx1 IPL ram_cs_b", false,-1);
        tracep->declBit(c+113,"top sharpx1 IPL wren_b", false,-1);
        tracep->declBus(c+114,"top sharpx1 IPL address_b", false,-1, 12,0);
        tracep->declBus(c+115,"top sharpx1 IPL data_b", false,-1, 7,0);
        tracep->declBus(c+116,"top sharpx1 IPL q_b", false,-1, 7,0);
        tracep->declBus(c+458,"top sharpx1 RAM data_width_g", false,-1, 31,0);
        tracep->declBus(c+460,"top sharpx1 RAM addr_width_g", false,-1, 31,0);
        tracep->declBit(c+117,"top sharpx1 RAM clock", false,-1);
        tracep->declBit(c+118,"top sharpx1 RAM ram_cs", false,-1);
        tracep->declBit(c+119,"top sharpx1 RAM wren_a", false,-1);
        tracep->declBus(c+120,"top sharpx1 RAM address_a", false,-1, 15,0);
        tracep->declBus(c+121,"top sharpx1 RAM data_a", false,-1, 7,0);
        tracep->declBus(c+122,"top sharpx1 RAM q_a", false,-1, 7,0);
        tracep->declBit(c+123,"top sharpx1 RAM ram_cs_b", false,-1);
        tracep->declBit(c+124,"top sharpx1 RAM wren_b", false,-1);
        tracep->declBus(c+125,"top sharpx1 RAM address_b", false,-1, 15,0);
        tracep->declBus(c+126,"top sharpx1 RAM data_b", false,-1, 7,0);
        tracep->declBus(c+127,"top sharpx1 RAM q_b", false,-1, 7,0);
        tracep->declBus(c+458,"top sharpx1 VRAM data_width_g", false,-1, 31,0);
        tracep->declBus(c+461,"top sharpx1 VRAM addr_width_g", false,-1, 31,0);
        tracep->declBit(c+128,"top sharpx1 VRAM clock", false,-1);
        tracep->declBit(c+129,"top sharpx1 VRAM ram_cs", false,-1);
        tracep->declBit(c+130,"top sharpx1 VRAM wren_a", false,-1);
        tracep->declBus(c+131,"top sharpx1 VRAM address_a", false,-1, 11,0);
        tracep->declBus(c+132,"top sharpx1 VRAM data_a", false,-1, 7,0);
        tracep->declBus(c+133,"top sharpx1 VRAM q_a", false,-1, 7,0);
        tracep->declBit(c+134,"top sharpx1 VRAM ram_cs_b", false,-1);
        tracep->declBit(c+135,"top sharpx1 VRAM wren_b", false,-1);
        tracep->declBus(c+136,"top sharpx1 VRAM address_b", false,-1, 11,0);
        tracep->declBus(c+137,"top sharpx1 VRAM data_b", false,-1, 7,0);
        tracep->declBus(c+138,"top sharpx1 VRAM q_b", false,-1, 7,0);
        tracep->declBus(c+458,"top sharpx1 PCGRAM data_width_g", false,-1, 31,0);
        tracep->declBus(c+459,"top sharpx1 PCGRAM addr_width_g", false,-1, 31,0);
        tracep->declBit(c+139,"top sharpx1 PCGRAM clock", false,-1);
        tracep->declBit(c+140,"top sharpx1 PCGRAM ram_cs", false,-1);
        tracep->declBit(c+141,"top sharpx1 PCGRAM wren_a", false,-1);
        tracep->declBus(c+142,"top sharpx1 PCGRAM address_a", false,-1, 12,0);
        tracep->declBus(c+143,"top sharpx1 PCGRAM data_a", false,-1, 7,0);
        tracep->declBus(c+144,"top sharpx1 PCGRAM q_a", false,-1, 7,0);
        tracep->declBit(c+145,"top sharpx1 PCGRAM ram_cs_b", false,-1);
        tracep->declBit(c+146,"top sharpx1 PCGRAM wren_b", false,-1);
        tracep->declBus(c+147,"top sharpx1 PCGRAM address_b", false,-1, 12,0);
        tracep->declBus(c+148,"top sharpx1 PCGRAM data_b", false,-1, 7,0);
        tracep->declBus(c+149,"top sharpx1 PCGRAM q_b", false,-1, 7,0);
        tracep->declBus(c+458,"top sharpx1 GRAM data_width_g", false,-1, 31,0);
        tracep->declBus(c+460,"top sharpx1 GRAM addr_width_g", false,-1, 31,0);
        tracep->declBit(c+150,"top sharpx1 GRAM clock", false,-1);
        tracep->declBit(c+151,"top sharpx1 GRAM ram_cs", false,-1);
        tracep->declBit(c+152,"top sharpx1 GRAM wren_a", false,-1);
        tracep->declBus(c+153,"top sharpx1 GRAM address_a", false,-1, 15,0);
        tracep->declBus(c+154,"top sharpx1 GRAM data_a", false,-1, 7,0);
        tracep->declBus(c+155,"top sharpx1 GRAM q_a", false,-1, 7,0);
        tracep->declBit(c+156,"top sharpx1 GRAM ram_cs_b", false,-1);
        tracep->declBit(c+157,"top sharpx1 GRAM wren_b", false,-1);
        tracep->declBus(c+158,"top sharpx1 GRAM address_b", false,-1, 15,0);
        tracep->declBus(c+159,"top sharpx1 GRAM data_b", false,-1, 7,0);
        tracep->declBus(c+160,"top sharpx1 GRAM q_b", false,-1, 7,0);
        tracep->declBit(c+161,"top sharpx1 Cpu reset_n", false,-1);
        tracep->declBit(c+162,"top sharpx1 Cpu clock", false,-1);
        tracep->declBit(c+163,"top sharpx1 Cpu cep", false,-1);
        tracep->declBit(c+164,"top sharpx1 Cpu cen", false,-1);
        tracep->declBit(c+165,"top sharpx1 Cpu int_n", false,-1);
        tracep->declBit(c+166,"top sharpx1 Cpu halt_n", false,-1);
        tracep->declBit(c+167,"top sharpx1 Cpu mreq", false,-1);
        tracep->declBit(c+168,"top sharpx1 Cpu iorq", false,-1);
        tracep->declBit(c+169,"top sharpx1 Cpu wr", false,-1);
        tracep->declBit(c+170,"top sharpx1 Cpu rd", false,-1);
        tracep->declBit(c+171,"top sharpx1 Cpu m1", false,-1);
        tracep->declBus(c+172,"top sharpx1 Cpu di", false,-1, 7,0);
        tracep->declBus(c+173,"top sharpx1 Cpu data_out", false,-1, 7,0);
        tracep->declBus(c+174,"top sharpx1 Cpu a", false,-1, 15,0);
        tracep->declBus(c+175,"top sharpx1 Cpu dir", false,-1, 15,0);
        tracep->declBit(c+176,"top sharpx1 Cpu dirset", false,-1);
        tracep->declBus(c+462,"top sharpx1 Cpu Z80CPU Mode", false,-1, 31,0);
        tracep->declBus(c+463,"top sharpx1 Cpu Z80CPU T2Write", false,-1, 31,0);
        tracep->declBus(c+463,"top sharpx1 Cpu Z80CPU IOWait", false,-1, 31,0);
        tracep->declBit(c+177,"top sharpx1 Cpu Z80CPU reset_n", false,-1);
        tracep->declBit(c+178,"top sharpx1 Cpu Z80CPU clk", false,-1);
        tracep->declBit(c+179,"top sharpx1 Cpu Z80CPU cen", false,-1);
        tracep->declBit(c+180,"top sharpx1 Cpu Z80CPU wait_n", false,-1);
        tracep->declBit(c+181,"top sharpx1 Cpu Z80CPU int_n", false,-1);
        tracep->declBit(c+182,"top sharpx1 Cpu Z80CPU nmi_n", false,-1);
        tracep->declBit(c+183,"top sharpx1 Cpu Z80CPU busrq_n", false,-1);
        tracep->declBit(c+184,"top sharpx1 Cpu Z80CPU m1_n", false,-1);
        tracep->declBit(c+185,"top sharpx1 Cpu Z80CPU mreq_n", false,-1);
        tracep->declBit(c+186,"top sharpx1 Cpu Z80CPU iorq_n", false,-1);
        tracep->declBit(c+187,"top sharpx1 Cpu Z80CPU rd_n", false,-1);
        tracep->declBit(c+188,"top sharpx1 Cpu Z80CPU wr_n", false,-1);
        tracep->declBit(c+189,"top sharpx1 Cpu Z80CPU rfsh_n", false,-1);
        tracep->declBit(c+190,"top sharpx1 Cpu Z80CPU halt_n", false,-1);
        tracep->declBit(c+191,"top sharpx1 Cpu Z80CPU busak_n", false,-1);
        tracep->declBus(c+192,"top sharpx1 Cpu Z80CPU A", false,-1, 15,0);
        tracep->declBus(c+193,"top sharpx1 Cpu Z80CPU di", false,-1, 7,0);
        tracep->declBus(c+194,"top sharpx1 Cpu Z80CPU dout", false,-1, 7,0);
        tracep->declBus(c+195,"top sharpx1 Cpu Z80CPU dir", false,-1, 15,0);
        tracep->declBit(c+196,"top sharpx1 Cpu Z80CPU dirset", false,-1);
        tracep->declBit(c+197,"top sharpx1 Cpu Z80CPU intcycle_n", false,-1);
        tracep->declBit(c+198,"top sharpx1 Cpu Z80CPU no_read", false,-1);
        tracep->declBit(c+199,"top sharpx1 Cpu Z80CPU write", false,-1);
        tracep->declBit(c+200,"top sharpx1 Cpu Z80CPU iorq", false,-1);
        tracep->declBus(c+201,"top sharpx1 Cpu Z80CPU di_reg", false,-1, 7,0);
        tracep->declBus(c+202,"top sharpx1 Cpu Z80CPU mcycle", false,-1, 6,0);
        tracep->declBus(c+203,"top sharpx1 Cpu Z80CPU tstate", false,-1, 6,0);
        tracep->declBus(c+462,"top sharpx1 Cpu Z80CPU i_tv80_core Mode", false,-1, 31,0);
        tracep->declBus(c+463,"top sharpx1 Cpu Z80CPU i_tv80_core IOWait", false,-1, 31,0);
        tracep->declBus(c+462,"top sharpx1 Cpu Z80CPU i_tv80_core Flag_C", false,-1, 31,0);
        tracep->declBus(c+463,"top sharpx1 Cpu Z80CPU i_tv80_core Flag_N", false,-1, 31,0);
        tracep->declBus(c+464,"top sharpx1 Cpu Z80CPU i_tv80_core Flag_P", false,-1, 31,0);
        tracep->declBus(c+465,"top sharpx1 Cpu Z80CPU i_tv80_core Flag_X", false,-1, 31,0);
        tracep->declBus(c+466,"top sharpx1 Cpu Z80CPU i_tv80_core Flag_H", false,-1, 31,0);
        tracep->declBus(c+467,"top sharpx1 Cpu Z80CPU i_tv80_core Flag_Y", false,-1, 31,0);
        tracep->declBus(c+468,"top sharpx1 Cpu Z80CPU i_tv80_core Flag_Z", false,-1, 31,0);
        tracep->declBus(c+469,"top sharpx1 Cpu Z80CPU i_tv80_core Flag_S", false,-1, 31,0);
        tracep->declBit(c+204,"top sharpx1 Cpu Z80CPU i_tv80_core reset_n", false,-1);
        tracep->declBit(c+205,"top sharpx1 Cpu Z80CPU i_tv80_core clk", false,-1);
        tracep->declBit(c+206,"top sharpx1 Cpu Z80CPU i_tv80_core cen", false,-1);
        tracep->declBit(c+207,"top sharpx1 Cpu Z80CPU i_tv80_core wait_n", false,-1);
        tracep->declBit(c+208,"top sharpx1 Cpu Z80CPU i_tv80_core int_n", false,-1);
        tracep->declBit(c+209,"top sharpx1 Cpu Z80CPU i_tv80_core nmi_n", false,-1);
        tracep->declBit(c+210,"top sharpx1 Cpu Z80CPU i_tv80_core busrq_n", false,-1);
        tracep->declBit(c+211,"top sharpx1 Cpu Z80CPU i_tv80_core m1_n", false,-1);
        tracep->declBit(c+212,"top sharpx1 Cpu Z80CPU i_tv80_core iorq", false,-1);
        tracep->declBit(c+213,"top sharpx1 Cpu Z80CPU i_tv80_core no_read", false,-1);
        tracep->declBit(c+214,"top sharpx1 Cpu Z80CPU i_tv80_core write", false,-1);
        tracep->declBit(c+215,"top sharpx1 Cpu Z80CPU i_tv80_core rfsh_n", false,-1);
        tracep->declBit(c+216,"top sharpx1 Cpu Z80CPU i_tv80_core halt_n", false,-1);
        tracep->declBit(c+217,"top sharpx1 Cpu Z80CPU i_tv80_core busak_n", false,-1);
        tracep->declBus(c+218,"top sharpx1 Cpu Z80CPU i_tv80_core A", false,-1, 15,0);
        tracep->declBus(c+219,"top sharpx1 Cpu Z80CPU i_tv80_core dinst", false,-1, 7,0);
        tracep->declBus(c+220,"top sharpx1 Cpu Z80CPU i_tv80_core di", false,-1, 7,0);
        tracep->declBus(c+221,"top sharpx1 Cpu Z80CPU i_tv80_core dout", false,-1, 7,0);
        tracep->declBus(c+222,"top sharpx1 Cpu Z80CPU i_tv80_core mc", false,-1, 6,0);
        tracep->declBus(c+223,"top sharpx1 Cpu Z80CPU i_tv80_core ts", false,-1, 6,0);
        tracep->declBit(c+224,"top sharpx1 Cpu Z80CPU i_tv80_core intcycle_n", false,-1);
        tracep->declBit(c+225,"top sharpx1 Cpu Z80CPU i_tv80_core IntE", false,-1);
        tracep->declBit(c+226,"top sharpx1 Cpu Z80CPU i_tv80_core stop", false,-1);
        tracep->declBus(c+227,"top sharpx1 Cpu Z80CPU i_tv80_core dir", false,-1, 15,0);
        tracep->declBit(c+228,"top sharpx1 Cpu Z80CPU i_tv80_core dirset", false,-1);
        tracep->declBus(c+470,"top sharpx1 Cpu Z80CPU i_tv80_core aNone", false,-1, 2,0);
        tracep->declBus(c+471,"top sharpx1 Cpu Z80CPU i_tv80_core aBC", false,-1, 2,0);
        tracep->declBus(c+472,"top sharpx1 Cpu Z80CPU i_tv80_core aDE", false,-1, 2,0);
        tracep->declBus(c+473,"top sharpx1 Cpu Z80CPU i_tv80_core aXY", false,-1, 2,0);
        tracep->declBus(c+474,"top sharpx1 Cpu Z80CPU i_tv80_core aIOA", false,-1, 2,0);
        tracep->declBus(c+475,"top sharpx1 Cpu Z80CPU i_tv80_core aSP", false,-1, 2,0);
        tracep->declBus(c+476,"top sharpx1 Cpu Z80CPU i_tv80_core aZI", false,-1, 2,0);
        tracep->declBus(c+229,"top sharpx1 Cpu Z80CPU i_tv80_core ACC", false,-1, 7,0);
        tracep->declBus(c+230,"top sharpx1 Cpu Z80CPU i_tv80_core F", false,-1, 7,0);
        tracep->declBus(c+231,"top sharpx1 Cpu Z80CPU i_tv80_core Ap", false,-1, 7,0);
        tracep->declBus(c+232,"top sharpx1 Cpu Z80CPU i_tv80_core Fp", false,-1, 7,0);
        tracep->declBus(c+233,"top sharpx1 Cpu Z80CPU i_tv80_core I", false,-1, 7,0);
        tracep->declBus(c+234,"top sharpx1 Cpu Z80CPU i_tv80_core SP", false,-1, 15,0);
        tracep->declBus(c+235,"top sharpx1 Cpu Z80CPU i_tv80_core PC", false,-1, 15,0);
        tracep->declBus(c+236,"top sharpx1 Cpu Z80CPU i_tv80_core RegDIH", false,-1, 7,0);
        tracep->declBus(c+237,"top sharpx1 Cpu Z80CPU i_tv80_core RegDIL", false,-1, 7,0);
        tracep->declBus(c+238,"top sharpx1 Cpu Z80CPU i_tv80_core RegBusA", false,-1, 15,0);
        tracep->declBus(c+239,"top sharpx1 Cpu Z80CPU i_tv80_core RegBusB", false,-1, 15,0);
        tracep->declBus(c+240,"top sharpx1 Cpu Z80CPU i_tv80_core RegBusC", false,-1, 15,0);
        tracep->declBus(c+241,"top sharpx1 Cpu Z80CPU i_tv80_core RegAddrA_r", false,-1, 2,0);
        tracep->declBus(c+242,"top sharpx1 Cpu Z80CPU i_tv80_core RegAddrA", false,-1, 2,0);
        tracep->declBus(c+243,"top sharpx1 Cpu Z80CPU i_tv80_core RegAddrB_r", false,-1, 2,0);
        tracep->declBus(c+244,"top sharpx1 Cpu Z80CPU i_tv80_core RegAddrB", false,-1, 2,0);
        tracep->declBus(c+245,"top sharpx1 Cpu Z80CPU i_tv80_core RegAddrC", false,-1, 2,0);
        tracep->declBit(c+246,"top sharpx1 Cpu Z80CPU i_tv80_core RegWEH", false,-1);
        tracep->declBit(c+247,"top sharpx1 Cpu Z80CPU i_tv80_core RegWEL", false,-1);
        tracep->declBit(c+248,"top sharpx1 Cpu Z80CPU i_tv80_core Alternate", false,-1);
        tracep->declBus(c+249,"top sharpx1 Cpu Z80CPU i_tv80_core TmpAddr", false,-1, 15,0);
        tracep->declBus(c+250,"top sharpx1 Cpu Z80CPU i_tv80_core IR", false,-1, 7,0);
        tracep->declBus(c+251,"top sharpx1 Cpu Z80CPU i_tv80_core ISet", false,-1, 1,0);
        tracep->declBus(c+252,"top sharpx1 Cpu Z80CPU i_tv80_core RegBusA_r", false,-1, 15,0);
        tracep->declBus(c+253,"top sharpx1 Cpu Z80CPU i_tv80_core ID16", false,-1, 15,0);
        tracep->declBus(c+254,"top sharpx1 Cpu Z80CPU i_tv80_core Save_Mux", false,-1, 7,0);
        tracep->declBus(c+255,"top sharpx1 Cpu Z80CPU i_tv80_core tstate", false,-1, 6,0);
        tracep->declBus(c+256,"top sharpx1 Cpu Z80CPU i_tv80_core mcycle", false,-1, 6,0);
        tracep->declBit(c+257,"top sharpx1 Cpu Z80CPU i_tv80_core last_mcycle", false,-1);
        tracep->declBit(c+258,"top sharpx1 Cpu Z80CPU i_tv80_core last_tstate", false,-1);
        tracep->declBit(c+259,"top sharpx1 Cpu Z80CPU i_tv80_core IntE_FF1", false,-1);
        tracep->declBit(c+260,"top sharpx1 Cpu Z80CPU i_tv80_core IntE_FF2", false,-1);
        tracep->declBit(c+261,"top sharpx1 Cpu Z80CPU i_tv80_core Halt_FF", false,-1);
        tracep->declBit(c+262,"top sharpx1 Cpu Z80CPU i_tv80_core BusReq_s", false,-1);
        tracep->declBit(c+263,"top sharpx1 Cpu Z80CPU i_tv80_core BusAck", false,-1);
        tracep->declBit(c+264,"top sharpx1 Cpu Z80CPU i_tv80_core ClkEn", false,-1);
        tracep->declBit(c+265,"top sharpx1 Cpu Z80CPU i_tv80_core NMI_s", false,-1);
        tracep->declBit(c+266,"top sharpx1 Cpu Z80CPU i_tv80_core INT_s", false,-1);
        tracep->declBus(c+267,"top sharpx1 Cpu Z80CPU i_tv80_core IStatus", false,-1, 1,0);
        tracep->declBus(c+268,"top sharpx1 Cpu Z80CPU i_tv80_core DI_Reg", false,-1, 7,0);
        tracep->declBit(c+269,"top sharpx1 Cpu Z80CPU i_tv80_core T_Res", false,-1);
        tracep->declBus(c+270,"top sharpx1 Cpu Z80CPU i_tv80_core XY_State", false,-1, 1,0);
        tracep->declBus(c+271,"top sharpx1 Cpu Z80CPU i_tv80_core Pre_XY_F_M", false,-1, 2,0);
        tracep->declBit(c+272,"top sharpx1 Cpu Z80CPU i_tv80_core NextIs_XY_Fetch", false,-1);
        tracep->declBit(c+273,"top sharpx1 Cpu Z80CPU i_tv80_core XY_Ind", false,-1);
        tracep->declBit(c+274,"top sharpx1 Cpu Z80CPU i_tv80_core No_BTR", false,-1);
        tracep->declBit(c+275,"top sharpx1 Cpu Z80CPU i_tv80_core BTR_r", false,-1);
        tracep->declBit(c+276,"top sharpx1 Cpu Z80CPU i_tv80_core Auto_Wait", false,-1);
        tracep->declBit(c+277,"top sharpx1 Cpu Z80CPU i_tv80_core Auto_Wait_t1", false,-1);
        tracep->declBit(c+278,"top sharpx1 Cpu Z80CPU i_tv80_core Auto_Wait_t2", false,-1);
        tracep->declBit(c+279,"top sharpx1 Cpu Z80CPU i_tv80_core IncDecZ", false,-1);
        tracep->declBus(c+280,"top sharpx1 Cpu Z80CPU i_tv80_core BusB", false,-1, 7,0);
        tracep->declBus(c+281,"top sharpx1 Cpu Z80CPU i_tv80_core BusA", false,-1, 7,0);
        tracep->declBus(c+282,"top sharpx1 Cpu Z80CPU i_tv80_core ALU_Q", false,-1, 7,0);
        tracep->declBus(c+283,"top sharpx1 Cpu Z80CPU i_tv80_core F_Out", false,-1, 7,0);
        tracep->declBus(c+284,"top sharpx1 Cpu Z80CPU i_tv80_core Read_To_Reg_r", false,-1, 4,0);
        tracep->declBit(c+285,"top sharpx1 Cpu Z80CPU i_tv80_core Arith16_r", false,-1);
        tracep->declBit(c+286,"top sharpx1 Cpu Z80CPU i_tv80_core Z16_r", false,-1);
        tracep->declBus(c+287,"top sharpx1 Cpu Z80CPU i_tv80_core ALU_Op_r", false,-1, 3,0);
        tracep->declBit(c+288,"top sharpx1 Cpu Z80CPU i_tv80_core Save_ALU_r", false,-1);
        tracep->declBit(c+289,"top sharpx1 Cpu Z80CPU i_tv80_core PreserveC_r", false,-1);
        tracep->declBus(c+290,"top sharpx1 Cpu Z80CPU i_tv80_core mcycles", false,-1, 2,0);
        tracep->declBus(c+291,"top sharpx1 Cpu Z80CPU i_tv80_core mcycles_d", false,-1, 2,0);
        tracep->declBus(c+292,"top sharpx1 Cpu Z80CPU i_tv80_core tstates", false,-1, 2,0);
        tracep->declBit(c+293,"top sharpx1 Cpu Z80CPU i_tv80_core IntCycle", false,-1);
        tracep->declBit(c+294,"top sharpx1 Cpu Z80CPU i_tv80_core NMICycle", false,-1);
        tracep->declBit(c+295,"top sharpx1 Cpu Z80CPU i_tv80_core Inc_PC", false,-1);
        tracep->declBit(c+296,"top sharpx1 Cpu Z80CPU i_tv80_core Inc_WZ", false,-1);
        tracep->declBus(c+297,"top sharpx1 Cpu Z80CPU i_tv80_core IncDec_16", false,-1, 3,0);
        tracep->declBus(c+298,"top sharpx1 Cpu Z80CPU i_tv80_core Prefix", false,-1, 1,0);
        tracep->declBit(c+299,"top sharpx1 Cpu Z80CPU i_tv80_core Read_To_Acc", false,-1);
        tracep->declBit(c+300,"top sharpx1 Cpu Z80CPU i_tv80_core Read_To_Reg", false,-1);
        tracep->declBus(c+301,"top sharpx1 Cpu Z80CPU i_tv80_core Set_BusB_To", false,-1, 3,0);
        tracep->declBus(c+302,"top sharpx1 Cpu Z80CPU i_tv80_core Set_BusA_To", false,-1, 3,0);
        tracep->declBus(c+303,"top sharpx1 Cpu Z80CPU i_tv80_core ALU_Op", false,-1, 3,0);
        tracep->declBit(c+304,"top sharpx1 Cpu Z80CPU i_tv80_core Save_ALU", false,-1);
        tracep->declBit(c+305,"top sharpx1 Cpu Z80CPU i_tv80_core PreserveC", false,-1);
        tracep->declBit(c+306,"top sharpx1 Cpu Z80CPU i_tv80_core Arith16", false,-1);
        tracep->declBus(c+307,"top sharpx1 Cpu Z80CPU i_tv80_core Set_Addr_To", false,-1, 2,0);
        tracep->declBit(c+308,"top sharpx1 Cpu Z80CPU i_tv80_core Jump", false,-1);
        tracep->declBit(c+309,"top sharpx1 Cpu Z80CPU i_tv80_core JumpE", false,-1);
        tracep->declBit(c+310,"top sharpx1 Cpu Z80CPU i_tv80_core JumpXY", false,-1);
        tracep->declBit(c+311,"top sharpx1 Cpu Z80CPU i_tv80_core Call", false,-1);
        tracep->declBit(c+312,"top sharpx1 Cpu Z80CPU i_tv80_core RstP", false,-1);
        tracep->declBit(c+313,"top sharpx1 Cpu Z80CPU i_tv80_core LDZ", false,-1);
        tracep->declBit(c+314,"top sharpx1 Cpu Z80CPU i_tv80_core LDW", false,-1);
        tracep->declBit(c+315,"top sharpx1 Cpu Z80CPU i_tv80_core LDSPHL", false,-1);
        tracep->declBit(c+316,"top sharpx1 Cpu Z80CPU i_tv80_core iorq_i", false,-1);
        tracep->declBus(c+317,"top sharpx1 Cpu Z80CPU i_tv80_core Special_LD", false,-1, 2,0);
        tracep->declBit(c+318,"top sharpx1 Cpu Z80CPU i_tv80_core ExchangeDH", false,-1);
        tracep->declBit(c+319,"top sharpx1 Cpu Z80CPU i_tv80_core ExchangeRp", false,-1);
        tracep->declBit(c+320,"top sharpx1 Cpu Z80CPU i_tv80_core ExchangeAF", false,-1);
        tracep->declBit(c+321,"top sharpx1 Cpu Z80CPU i_tv80_core ExchangeRS", false,-1);
        tracep->declBit(c+322,"top sharpx1 Cpu Z80CPU i_tv80_core I_DJNZ", false,-1);
        tracep->declBit(c+323,"top sharpx1 Cpu Z80CPU i_tv80_core I_CPL", false,-1);
        tracep->declBit(c+324,"top sharpx1 Cpu Z80CPU i_tv80_core I_CCF", false,-1);
        tracep->declBit(c+325,"top sharpx1 Cpu Z80CPU i_tv80_core I_SCF", false,-1);
        tracep->declBit(c+326,"top sharpx1 Cpu Z80CPU i_tv80_core I_RETN", false,-1);
        tracep->declBit(c+327,"top sharpx1 Cpu Z80CPU i_tv80_core I_BT", false,-1);
        tracep->declBit(c+328,"top sharpx1 Cpu Z80CPU i_tv80_core I_BC", false,-1);
        tracep->declBit(c+329,"top sharpx1 Cpu Z80CPU i_tv80_core I_BTR", false,-1);
        tracep->declBit(c+330,"top sharpx1 Cpu Z80CPU i_tv80_core I_RLD", false,-1);
        tracep->declBit(c+331,"top sharpx1 Cpu Z80CPU i_tv80_core I_RRD", false,-1);
        tracep->declBit(c+332,"top sharpx1 Cpu Z80CPU i_tv80_core I_INRC", false,-1);
        tracep->declBit(c+333,"top sharpx1 Cpu Z80CPU i_tv80_core SetDI", false,-1);
        tracep->declBit(c+334,"top sharpx1 Cpu Z80CPU i_tv80_core SetEI", false,-1);
        tracep->declBus(c+335,"top sharpx1 Cpu Z80CPU i_tv80_core IMode", false,-1, 1,0);
        tracep->declBit(c+336,"top sharpx1 Cpu Z80CPU i_tv80_core Halt", false,-1);
        tracep->declBus(c+337,"top sharpx1 Cpu Z80CPU i_tv80_core PC16", false,-1, 15,0);
        tracep->declBus(c+338,"top sharpx1 Cpu Z80CPU i_tv80_core PC16_B", false,-1, 15,0);
        tracep->declBus(c+339,"top sharpx1 Cpu Z80CPU i_tv80_core SP16", false,-1, 15,0);
        tracep->declBus(c+340,"top sharpx1 Cpu Z80CPU i_tv80_core SP16_A", false,-1, 15,0);
        tracep->declBus(c+341,"top sharpx1 Cpu Z80CPU i_tv80_core SP16_B", false,-1, 15,0);
        tracep->declBus(c+342,"top sharpx1 Cpu Z80CPU i_tv80_core ID16_B", false,-1, 15,0);
        tracep->declBit(c+343,"top sharpx1 Cpu Z80CPU i_tv80_core Oldnmi_n", false,-1);
        tracep->declBus(c+462,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Mode", false,-1, 31,0);
        tracep->declBus(c+462,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Flag_C", false,-1, 31,0);
        tracep->declBus(c+463,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Flag_N", false,-1, 31,0);
        tracep->declBus(c+464,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Flag_P", false,-1, 31,0);
        tracep->declBus(c+465,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Flag_X", false,-1, 31,0);
        tracep->declBus(c+466,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Flag_H", false,-1, 31,0);
        tracep->declBus(c+467,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Flag_Y", false,-1, 31,0);
        tracep->declBus(c+468,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Flag_Z", false,-1, 31,0);
        tracep->declBus(c+469,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Flag_S", false,-1, 31,0);
        tracep->declBus(c+344,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode IR", false,-1, 7,0);
        tracep->declBus(c+345,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode ISet", false,-1, 1,0);
        tracep->declBus(c+346,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode MCycle", false,-1, 6,0);
        tracep->declBus(c+347,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode F", false,-1, 7,0);
        tracep->declBit(c+348,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode NMICycle", false,-1);
        tracep->declBit(c+349,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode IntCycle", false,-1);
        tracep->declBus(c+350,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode MCycles", false,-1, 2,0);
        tracep->declBus(c+351,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode TStates", false,-1, 2,0);
        tracep->declBus(c+352,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Prefix", false,-1, 1,0);
        tracep->declBit(c+353,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Inc_PC", false,-1);
        tracep->declBit(c+354,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Inc_WZ", false,-1);
        tracep->declBus(c+355,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode IncDec_16", false,-1, 3,0);
        tracep->declBit(c+356,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Read_To_Reg", false,-1);
        tracep->declBit(c+357,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Read_To_Acc", false,-1);
        tracep->declBus(c+358,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Set_BusA_To", false,-1, 3,0);
        tracep->declBus(c+359,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Set_BusB_To", false,-1, 3,0);
        tracep->declBus(c+360,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode ALU_Op", false,-1, 3,0);
        tracep->declBit(c+361,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Save_ALU", false,-1);
        tracep->declBit(c+362,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode PreserveC", false,-1);
        tracep->declBit(c+363,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Arith16", false,-1);
        tracep->declBus(c+364,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Set_Addr_To", false,-1, 2,0);
        tracep->declBit(c+365,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode IORQ", false,-1);
        tracep->declBit(c+366,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Jump", false,-1);
        tracep->declBit(c+367,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode JumpE", false,-1);
        tracep->declBit(c+368,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode JumpXY", false,-1);
        tracep->declBit(c+369,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Call", false,-1);
        tracep->declBit(c+370,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode RstP", false,-1);
        tracep->declBit(c+371,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode LDZ", false,-1);
        tracep->declBit(c+372,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode LDW", false,-1);
        tracep->declBit(c+373,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode LDSPHL", false,-1);
        tracep->declBus(c+374,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Special_LD", false,-1, 2,0);
        tracep->declBit(c+375,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode ExchangeDH", false,-1);
        tracep->declBit(c+376,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode ExchangeRp", false,-1);
        tracep->declBit(c+377,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode ExchangeAF", false,-1);
        tracep->declBit(c+378,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode ExchangeRS", false,-1);
        tracep->declBit(c+379,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_DJNZ", false,-1);
        tracep->declBit(c+380,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_CPL", false,-1);
        tracep->declBit(c+381,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_CCF", false,-1);
        tracep->declBit(c+382,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_SCF", false,-1);
        tracep->declBit(c+383,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_RETN", false,-1);
        tracep->declBit(c+384,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_BT", false,-1);
        tracep->declBit(c+385,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_BC", false,-1);
        tracep->declBit(c+386,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_BTR", false,-1);
        tracep->declBit(c+387,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_RLD", false,-1);
        tracep->declBit(c+388,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_RRD", false,-1);
        tracep->declBit(c+389,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode I_INRC", false,-1);
        tracep->declBit(c+390,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode SetDI", false,-1);
        tracep->declBit(c+391,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode SetEI", false,-1);
        tracep->declBus(c+392,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode IMode", false,-1, 1,0);
        tracep->declBit(c+393,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Halt", false,-1);
        tracep->declBit(c+394,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode NoRead", false,-1);
        tracep->declBit(c+395,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode Write", false,-1);
        tracep->declBus(c+470,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode aNone", false,-1, 2,0);
        tracep->declBus(c+471,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode aBC", false,-1, 2,0);
        tracep->declBus(c+472,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode aDE", false,-1, 2,0);
        tracep->declBus(c+473,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode aXY", false,-1, 2,0);
        tracep->declBus(c+474,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode aIOA", false,-1, 2,0);
        tracep->declBus(c+475,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode aSP", false,-1, 2,0);
        tracep->declBus(c+476,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode aZI", false,-1, 2,0);
        tracep->declBus(c+396,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode DDD", false,-1, 2,0);
        tracep->declBus(c+397,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode SSS", false,-1, 2,0);
        tracep->declBus(c+398,"top sharpx1 Cpu Z80CPU i_tv80_core i_mcode DPAIR", false,-1, 1,0);
        tracep->declBus(c+462,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Mode", false,-1, 31,0);
        tracep->declBus(c+462,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Flag_C", false,-1, 31,0);
        tracep->declBus(c+463,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Flag_N", false,-1, 31,0);
        tracep->declBus(c+464,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Flag_P", false,-1, 31,0);
        tracep->declBus(c+465,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Flag_X", false,-1, 31,0);
        tracep->declBus(c+466,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Flag_H", false,-1, 31,0);
        tracep->declBus(c+467,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Flag_Y", false,-1, 31,0);
        tracep->declBus(c+468,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Flag_Z", false,-1, 31,0);
        tracep->declBus(c+469,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Flag_S", false,-1, 31,0);
        tracep->declBit(c+399,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Arith16", false,-1);
        tracep->declBit(c+400,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Z16", false,-1);
        tracep->declBus(c+401,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu ALU_Op", false,-1, 3,0);
        tracep->declBus(c+402,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu IR", false,-1, 5,0);
        tracep->declBus(c+403,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu ISet", false,-1, 1,0);
        tracep->declBus(c+404,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu BusA", false,-1, 7,0);
        tracep->declBus(c+405,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu BusB", false,-1, 7,0);
        tracep->declBus(c+406,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu F_In", false,-1, 7,0);
        tracep->declBus(c+407,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Q", false,-1, 7,0);
        tracep->declBus(c+408,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu F_Out", false,-1, 7,0);
        tracep->declBit(c+409,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu UseCarry", false,-1);
        tracep->declBit(c+410,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Carry7_v", false,-1);
        tracep->declBit(c+411,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu OverFlow_v", false,-1);
        tracep->declBit(c+412,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu HalfCarry_v", false,-1);
        tracep->declBit(c+413,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Carry_v", false,-1);
        tracep->declBus(c+414,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Q_v", false,-1, 7,0);
        tracep->declBus(c+415,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu BitMask", false,-1, 7,0);
        tracep->declBus(c+416,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu Q_t", false,-1, 7,0);
        tracep->declBus(c+417,"top sharpx1 Cpu Z80CPU i_tv80_core i_alu DAA_Q", false,-1, 8,0);
        tracep->declBus(c+418,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg AddrC", false,-1, 2,0);
        tracep->declBus(c+419,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg DOBH", false,-1, 7,0);
        tracep->declBus(c+420,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg AddrA", false,-1, 2,0);
        tracep->declBus(c+421,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg AddrB", false,-1, 2,0);
        tracep->declBus(c+422,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg DIH", false,-1, 7,0);
        tracep->declBus(c+423,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg DOAL", false,-1, 7,0);
        tracep->declBus(c+424,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg DOCL", false,-1, 7,0);
        tracep->declBus(c+425,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg DIL", false,-1, 7,0);
        tracep->declBus(c+426,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg DOBL", false,-1, 7,0);
        tracep->declBus(c+427,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg DOCH", false,-1, 7,0);
        tracep->declBus(c+428,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg DOAH", false,-1, 7,0);
        tracep->declBit(c+429,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg clk", false,-1);
        tracep->declBit(c+430,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg CEN", false,-1);
        tracep->declBit(c+431,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg WEH", false,-1);
        tracep->declBit(c+432,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg WEL", false,-1);
        tracep->declBit(c+433,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg DIRSET", false,-1);
        {int i; for (i=0; i<8; i++) {
                tracep->declBus(c+434+i*1,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg RegsH", true,(i+0), 7,0);}}
        {int i; for (i=0; i<8; i++) {
                tracep->declBus(c+442+i*1,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg RegsL", true,(i+0), 7,0);}}
        tracep->declBus(c+450,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg B", false,-1, 7,0);
        tracep->declBus(c+451,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg C", false,-1, 7,0);
        tracep->declBus(c+452,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg D", false,-1, 7,0);
        tracep->declBus(c+453,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg E", false,-1, 7,0);
        tracep->declBus(c+454,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg H", false,-1, 7,0);
        tracep->declBus(c+455,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg L", false,-1, 7,0);
        tracep->declBus(c+456,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg IX", false,-1, 15,0);
        tracep->declBus(c+457,"top sharpx1 Cpu Z80CPU i_tv80_core i_reg IY", false,-1, 15,0);
    }
}

void Vtop::traceRegister(VerilatedVcd* tracep) {
    // Body
    {
        tracep->addFullCb(&traceFullTop0, __VlSymsp);
        tracep->addChgCb(&traceChgTop0, __VlSymsp);
        tracep->addCleanupCb(&traceCleanup, __VlSymsp);
    }
}

void Vtop::traceFullTop0(void* userp, VerilatedVcd* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceFullSub0(userp, tracep);
    }
}

void Vtop::traceFullSub0(void* userp, VerilatedVcd* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        tracep->fullBit(oldp+1,(vlTOPp->clk_48));
        tracep->fullBit(oldp+2,(vlTOPp->clk_12));
        tracep->fullSData(oldp+3,(vlTOPp->inputs),12);
        tracep->fullCData(oldp+4,(vlTOPp->VGA_R),8);
        tracep->fullCData(oldp+5,(vlTOPp->VGA_G),8);
        tracep->fullCData(oldp+6,(vlTOPp->VGA_B),8);
        tracep->fullBit(oldp+7,(vlTOPp->VGA_HS));
        tracep->fullBit(oldp+8,(vlTOPp->VGA_VS));
        tracep->fullBit(oldp+9,(vlTOPp->VGA_HB));
        tracep->fullBit(oldp+10,(vlTOPp->VGA_VB));
        tracep->fullSData(oldp+11,(vlTOPp->AUDIO_L),16);
        tracep->fullSData(oldp+12,(vlTOPp->AUDIO_R),16);
        tracep->fullBit(oldp+13,(vlTOPp->ioctl_download));
        tracep->fullBit(oldp+14,(vlTOPp->ioctl_upload));
        tracep->fullBit(oldp+15,(vlTOPp->ioctl_wr));
        tracep->fullIData(oldp+16,(vlTOPp->ioctl_addr),25);
        tracep->fullCData(oldp+17,(vlTOPp->ioctl_dout),8);
        tracep->fullCData(oldp+18,(vlTOPp->ioctl_din),8);
        tracep->fullCData(oldp+19,(vlTOPp->ioctl_index),8);
        tracep->fullBit(oldp+20,(vlTOPp->ioctl_wait));
        tracep->fullBit(oldp+21,(vlTOPp->top__DOT__clk_48));
        tracep->fullBit(oldp+22,(vlTOPp->top__DOT__clk_12));
        tracep->fullSData(oldp+23,(vlTOPp->top__DOT__inputs),12);
        tracep->fullCData(oldp+24,(vlTOPp->top__DOT__VGA_R),8);
        tracep->fullCData(oldp+25,(vlTOPp->top__DOT__VGA_G),8);
        tracep->fullCData(oldp+26,(vlTOPp->top__DOT__VGA_B),8);
        tracep->fullBit(oldp+27,(vlTOPp->top__DOT__VGA_HS));
        tracep->fullBit(oldp+28,(vlTOPp->top__DOT__VGA_VS));
        tracep->fullBit(oldp+29,(vlTOPp->top__DOT__VGA_HB));
        tracep->fullBit(oldp+30,(vlTOPp->top__DOT__VGA_VB));
        tracep->fullSData(oldp+31,(vlTOPp->top__DOT__AUDIO_L),16);
        tracep->fullSData(oldp+32,(vlTOPp->top__DOT__AUDIO_R),16);
        tracep->fullBit(oldp+33,(vlTOPp->top__DOT__ioctl_download));
        tracep->fullBit(oldp+34,(vlTOPp->top__DOT__ioctl_upload));
        tracep->fullBit(oldp+35,(vlTOPp->top__DOT__ioctl_wr));
        tracep->fullIData(oldp+36,(vlTOPp->top__DOT__ioctl_addr),25);
        tracep->fullCData(oldp+37,(vlTOPp->top__DOT__ioctl_dout),8);
        tracep->fullCData(oldp+38,(vlTOPp->top__DOT__ioctl_din),8);
        tracep->fullCData(oldp+39,(vlTOPp->top__DOT__ioctl_index),8);
        tracep->fullBit(oldp+40,(vlTOPp->top__DOT__ioctl_wait));
        tracep->fullBit(oldp+41,(vlTOPp->top__DOT__pause));
        tracep->fullCData(oldp+42,(vlTOPp->top__DOT__audio),8);
        tracep->fullSData(oldp+43,(vlTOPp->top__DOT__rgb),9);
        tracep->fullCData(oldp+44,(vlTOPp->top__DOT__led),4);
        tracep->fullCData(oldp+45,(vlTOPp->top__DOT__trakball),8);
        tracep->fullCData(oldp+46,(vlTOPp->top__DOT__joystick),8);
        tracep->fullSData(oldp+47,(vlTOPp->top__DOT__playerinput),10);
        tracep->fullCData(oldp+48,(vlTOPp->top__DOT__sw1),8);
        tracep->fullCData(oldp+49,(vlTOPp->top__DOT__sw2),8);
        tracep->fullBit(oldp+50,(vlTOPp->top__DOT__ce_pix));
        tracep->fullBit(oldp+51,(vlTOPp->top__DOT__reset));
        tracep->fullBit(oldp+52,(vlTOPp->top__DOT__unnamedblk1__DOT__old_clk));
        tracep->fullBit(oldp+53,(vlTOPp->top__DOT__sharpx1__DOT__clk_sys));
        tracep->fullBit(oldp+54,(vlTOPp->top__DOT__sharpx1__DOT__clk_28636));
        tracep->fullBit(oldp+55,(vlTOPp->top__DOT__sharpx1__DOT__reset));
        tracep->fullBit(oldp+56,(vlTOPp->top__DOT__sharpx1__DOT__pal));
        tracep->fullBit(oldp+57,(vlTOPp->top__DOT__sharpx1__DOT__scandouble));
        tracep->fullBit(oldp+58,(vlTOPp->top__DOT__sharpx1__DOT__ioctl_download));
        tracep->fullCData(oldp+59,(vlTOPp->top__DOT__sharpx1__DOT__ioctl_index),8);
        tracep->fullBit(oldp+60,(vlTOPp->top__DOT__sharpx1__DOT__ioctl_wr));
        tracep->fullIData(oldp+61,(vlTOPp->top__DOT__sharpx1__DOT__ioctl_addr),25);
        tracep->fullCData(oldp+62,(vlTOPp->top__DOT__sharpx1__DOT__ioctl_dout),8);
        tracep->fullBit(oldp+63,(vlTOPp->top__DOT__sharpx1__DOT__ce_pix));
        tracep->fullBit(oldp+64,(vlTOPp->top__DOT__sharpx1__DOT__HBlank));
        tracep->fullBit(oldp+65,(vlTOPp->top__DOT__sharpx1__DOT__HSync));
        tracep->fullBit(oldp+66,(vlTOPp->top__DOT__sharpx1__DOT__VBlank));
        tracep->fullBit(oldp+67,(vlTOPp->top__DOT__sharpx1__DOT__VSync));
        tracep->fullCData(oldp+68,(vlTOPp->top__DOT__sharpx1__DOT__video),8);
        tracep->fullCData(oldp+69,(vlTOPp->top__DOT__sharpx1__DOT__romDo_SharpX1),8);
        tracep->fullSData(oldp+70,(vlTOPp->top__DOT__sharpx1__DOT__romA),14);
        tracep->fullCData(oldp+71,(vlTOPp->top__DOT__sharpx1__DOT__ramDi),8);
        tracep->fullCData(oldp+72,(vlTOPp->top__DOT__sharpx1__DOT__ramDo),8);
        tracep->fullSData(oldp+73,(vlTOPp->top__DOT__sharpx1__DOT__ramA),16);
        tracep->fullBit(oldp+74,(vlTOPp->top__DOT__sharpx1__DOT__ramWe));
        tracep->fullCData(oldp+75,(vlTOPp->top__DOT__sharpx1__DOT__vramDi),8);
        tracep->fullCData(oldp+76,(vlTOPp->top__DOT__sharpx1__DOT__vramDo),8);
        tracep->fullSData(oldp+77,(vlTOPp->top__DOT__sharpx1__DOT__vramA),16);
        tracep->fullBit(oldp+78,(vlTOPp->top__DOT__sharpx1__DOT__vramWe));
        tracep->fullCData(oldp+79,(vlTOPp->top__DOT__sharpx1__DOT__pcgramDi),8);
        tracep->fullCData(oldp+80,(vlTOPp->top__DOT__sharpx1__DOT__pcgramDo),8);
        tracep->fullSData(oldp+81,(vlTOPp->top__DOT__sharpx1__DOT__pcgvramA),16);
        tracep->fullBit(oldp+82,(vlTOPp->top__DOT__sharpx1__DOT__pcgramWe));
        tracep->fullCData(oldp+83,(vlTOPp->top__DOT__sharpx1__DOT__gramDi),8);
        tracep->fullCData(oldp+84,(vlTOPp->top__DOT__sharpx1__DOT__gramDo),8);
        tracep->fullSData(oldp+85,(vlTOPp->top__DOT__sharpx1__DOT__gramA),16);
        tracep->fullBit(oldp+86,(vlTOPp->top__DOT__sharpx1__DOT__gramWe));
        tracep->fullCData(oldp+87,(vlTOPp->top__DOT__sharpx1__DOT__ce),4);
        tracep->fullBit(oldp+88,(vlTOPp->top__DOT__sharpx1__DOT__pe8M8));
        tracep->fullBit(oldp+89,(vlTOPp->top__DOT__sharpx1__DOT__ne8M8));
        tracep->fullBit(oldp+90,(vlTOPp->top__DOT__sharpx1__DOT__pe4M4));
        tracep->fullBit(oldp+91,(vlTOPp->top__DOT__sharpx1__DOT__ne4M4));
        tracep->fullBit(oldp+92,(vlTOPp->top__DOT__sharpx1__DOT__pe2M2));
        tracep->fullBit(oldp+93,(vlTOPp->top__DOT__sharpx1__DOT__ne2M2));
        tracep->fullBit(oldp+94,(vlTOPp->top__DOT__sharpx1__DOT__pe1M1));
        tracep->fullBit(oldp+95,(vlTOPp->top__DOT__sharpx1__DOT__ne1M1));
        tracep->fullCData(oldp+96,(vlTOPp->top__DOT__sharpx1__DOT__di),8);
        tracep->fullCData(oldp+97,(vlTOPp->top__DOT__sharpx1__DOT__data_out),8);
        tracep->fullSData(oldp+98,(vlTOPp->top__DOT__sharpx1__DOT__a),16);
        tracep->fullBit(oldp+99,(vlTOPp->top__DOT__sharpx1__DOT__mreq));
        tracep->fullBit(oldp+100,(vlTOPp->top__DOT__sharpx1__DOT__iorq));
        tracep->fullBit(oldp+101,(vlTOPp->top__DOT__sharpx1__DOT__wr));
        tracep->fullBit(oldp+102,(vlTOPp->top__DOT__sharpx1__DOT__rd));
        tracep->fullSData(oldp+103,(vlTOPp->top__DOT__sharpx1__DOT__dir),16);
        tracep->fullBit(oldp+104,(vlTOPp->top__DOT__sharpx1__DOT__dirset));
        tracep->fullBit(oldp+105,(vlTOPp->top__DOT__sharpx1__DOT__m1));
        tracep->fullBit(oldp+106,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__clock));
        tracep->fullBit(oldp+107,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__ram_cs));
        tracep->fullBit(oldp+108,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__wren_a));
        tracep->fullSData(oldp+109,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__address_a),13);
        tracep->fullCData(oldp+110,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__data_a),8);
        tracep->fullCData(oldp+111,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__q_a),8);
        tracep->fullBit(oldp+112,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__ram_cs_b));
        tracep->fullBit(oldp+113,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__wren_b));
        tracep->fullSData(oldp+114,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__address_b),13);
        tracep->fullCData(oldp+115,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__data_b),8);
        tracep->fullCData(oldp+116,(vlTOPp->top__DOT__sharpx1__DOT__IPL__DOT__q_b),8);
        tracep->fullBit(oldp+117,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__clock));
        tracep->fullBit(oldp+118,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__ram_cs));
        tracep->fullBit(oldp+119,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__wren_a));
        tracep->fullSData(oldp+120,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__address_a),16);
        tracep->fullCData(oldp+121,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__data_a),8);
        tracep->fullCData(oldp+122,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__q_a),8);
        tracep->fullBit(oldp+123,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__ram_cs_b));
        tracep->fullBit(oldp+124,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__wren_b));
        tracep->fullSData(oldp+125,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__address_b),16);
        tracep->fullCData(oldp+126,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__data_b),8);
        tracep->fullCData(oldp+127,(vlTOPp->top__DOT__sharpx1__DOT__RAM__DOT__q_b),8);
        tracep->fullBit(oldp+128,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__clock));
        tracep->fullBit(oldp+129,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__ram_cs));
        tracep->fullBit(oldp+130,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__wren_a));
        tracep->fullSData(oldp+131,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__address_a),12);
        tracep->fullCData(oldp+132,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__data_a),8);
        tracep->fullCData(oldp+133,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__q_a),8);
        tracep->fullBit(oldp+134,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__ram_cs_b));
        tracep->fullBit(oldp+135,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__wren_b));
        tracep->fullSData(oldp+136,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__address_b),12);
        tracep->fullCData(oldp+137,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__data_b),8);
        tracep->fullCData(oldp+138,(vlTOPp->top__DOT__sharpx1__DOT__VRAM__DOT__q_b),8);
        tracep->fullBit(oldp+139,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__clock));
        tracep->fullBit(oldp+140,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__ram_cs));
        tracep->fullBit(oldp+141,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__wren_a));
        tracep->fullSData(oldp+142,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__address_a),13);
        tracep->fullCData(oldp+143,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__data_a),8);
        tracep->fullCData(oldp+144,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__q_a),8);
        tracep->fullBit(oldp+145,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__ram_cs_b));
        tracep->fullBit(oldp+146,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__wren_b));
        tracep->fullSData(oldp+147,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__address_b),13);
        tracep->fullCData(oldp+148,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__data_b),8);
        tracep->fullCData(oldp+149,(vlTOPp->top__DOT__sharpx1__DOT__PCGRAM__DOT__q_b),8);
        tracep->fullBit(oldp+150,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__clock));
        tracep->fullBit(oldp+151,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__ram_cs));
        tracep->fullBit(oldp+152,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__wren_a));
        tracep->fullSData(oldp+153,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__address_a),16);
        tracep->fullCData(oldp+154,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__data_a),8);
        tracep->fullCData(oldp+155,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__q_a),8);
        tracep->fullBit(oldp+156,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__ram_cs_b));
        tracep->fullBit(oldp+157,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__wren_b));
        tracep->fullSData(oldp+158,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__address_b),16);
        tracep->fullCData(oldp+159,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__data_b),8);
        tracep->fullCData(oldp+160,(vlTOPp->top__DOT__sharpx1__DOT__GRAM__DOT__q_b),8);
        tracep->fullBit(oldp+161,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__reset_n));
        tracep->fullBit(oldp+162,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__clock));
        tracep->fullBit(oldp+163,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__cep));
        tracep->fullBit(oldp+164,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__cen));
        tracep->fullBit(oldp+165,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__int_n));
        tracep->fullBit(oldp+166,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__halt_n));
        tracep->fullBit(oldp+167,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__mreq));
        tracep->fullBit(oldp+168,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__iorq));
        tracep->fullBit(oldp+169,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__wr));
        tracep->fullBit(oldp+170,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__rd));
        tracep->fullBit(oldp+171,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__m1));
        tracep->fullCData(oldp+172,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__di),8);
        tracep->fullCData(oldp+173,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__data_out),8);
        tracep->fullSData(oldp+174,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__a),16);
        tracep->fullSData(oldp+175,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__dir),16);
        tracep->fullBit(oldp+176,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__dirset));
        tracep->fullBit(oldp+177,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__reset_n));
        tracep->fullBit(oldp+178,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__clk));
        tracep->fullBit(oldp+179,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__cen));
        tracep->fullBit(oldp+180,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__wait_n));
        tracep->fullBit(oldp+181,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__int_n));
        tracep->fullBit(oldp+182,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__nmi_n));
        tracep->fullBit(oldp+183,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__busrq_n));
        tracep->fullBit(oldp+184,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__m1_n));
        tracep->fullBit(oldp+185,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__mreq_n));
        tracep->fullBit(oldp+186,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__iorq_n));
        tracep->fullBit(oldp+187,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__rd_n));
        tracep->fullBit(oldp+188,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__wr_n));
        tracep->fullBit(oldp+189,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__rfsh_n));
        tracep->fullBit(oldp+190,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__halt_n));
        tracep->fullBit(oldp+191,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__busak_n));
        tracep->fullSData(oldp+192,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__A),16);
        tracep->fullCData(oldp+193,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__di),8);
        tracep->fullCData(oldp+194,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__dout),8);
        tracep->fullSData(oldp+195,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__dir),16);
        tracep->fullBit(oldp+196,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__dirset));
        tracep->fullBit(oldp+197,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__intcycle_n));
        tracep->fullBit(oldp+198,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__no_read));
        tracep->fullBit(oldp+199,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__write));
        tracep->fullBit(oldp+200,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__iorq));
        tracep->fullCData(oldp+201,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__di_reg),8);
        tracep->fullCData(oldp+202,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__mcycle),7);
        tracep->fullCData(oldp+203,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__tstate),7);
        tracep->fullBit(oldp+204,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__reset_n));
        tracep->fullBit(oldp+205,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__clk));
        tracep->fullBit(oldp+206,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__cen));
        tracep->fullBit(oldp+207,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__wait_n));
        tracep->fullBit(oldp+208,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__int_n));
        tracep->fullBit(oldp+209,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__nmi_n));
        tracep->fullBit(oldp+210,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__busrq_n));
        tracep->fullBit(oldp+211,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__m1_n));
        tracep->fullBit(oldp+212,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__iorq));
        tracep->fullBit(oldp+213,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__no_read));
        tracep->fullBit(oldp+214,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__write));
        tracep->fullBit(oldp+215,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__rfsh_n));
        tracep->fullBit(oldp+216,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__halt_n));
        tracep->fullBit(oldp+217,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__busak_n));
        tracep->fullSData(oldp+218,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__A),16);
        tracep->fullCData(oldp+219,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__dinst),8);
        tracep->fullCData(oldp+220,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__di),8);
        tracep->fullCData(oldp+221,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__dout),8);
        tracep->fullCData(oldp+222,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__mc),7);
        tracep->fullCData(oldp+223,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ts),7);
        tracep->fullBit(oldp+224,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__intcycle_n));
        tracep->fullBit(oldp+225,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__IntE));
        tracep->fullBit(oldp+226,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__stop));
        tracep->fullSData(oldp+227,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__dir),16);
        tracep->fullBit(oldp+228,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__dirset));
        tracep->fullCData(oldp+229,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ACC),8);
        tracep->fullCData(oldp+230,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__F),8);
        tracep->fullCData(oldp+231,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Ap),8);
        tracep->fullCData(oldp+232,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Fp),8);
        tracep->fullCData(oldp+233,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I),8);
        tracep->fullSData(oldp+234,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__SP),16);
        tracep->fullSData(oldp+235,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__PC),16);
        tracep->fullCData(oldp+236,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegDIH),8);
        tracep->fullCData(oldp+237,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegDIL),8);
        tracep->fullSData(oldp+238,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegBusA),16);
        tracep->fullSData(oldp+239,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegBusB),16);
        tracep->fullSData(oldp+240,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegBusC),16);
        tracep->fullCData(oldp+241,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegAddrA_r),3);
        tracep->fullCData(oldp+242,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegAddrA),3);
        tracep->fullCData(oldp+243,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegAddrB_r),3);
        tracep->fullCData(oldp+244,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegAddrB),3);
        tracep->fullCData(oldp+245,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegAddrC),3);
        tracep->fullBit(oldp+246,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegWEH));
        tracep->fullBit(oldp+247,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegWEL));
        tracep->fullBit(oldp+248,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Alternate));
        tracep->fullSData(oldp+249,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__TmpAddr),16);
        tracep->fullCData(oldp+250,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__IR),8);
        tracep->fullCData(oldp+251,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ISet),2);
        tracep->fullSData(oldp+252,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RegBusA_r),16);
        tracep->fullSData(oldp+253,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ID16),16);
        tracep->fullCData(oldp+254,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Save_Mux),8);
        tracep->fullCData(oldp+255,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__tstate),7);
        tracep->fullCData(oldp+256,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__mcycle),7);
        tracep->fullBit(oldp+257,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__last_mcycle));
        tracep->fullBit(oldp+258,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__last_tstate));
        tracep->fullBit(oldp+259,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__IntE_FF1));
        tracep->fullBit(oldp+260,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__IntE_FF2));
        tracep->fullBit(oldp+261,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Halt_FF));
        tracep->fullBit(oldp+262,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__BusReq_s));
        tracep->fullBit(oldp+263,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__BusAck));
        tracep->fullBit(oldp+264,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ClkEn));
        tracep->fullBit(oldp+265,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__NMI_s));
        tracep->fullBit(oldp+266,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__INT_s));
        tracep->fullCData(oldp+267,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__IStatus),2);
        tracep->fullCData(oldp+268,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__DI_Reg),8);
        tracep->fullBit(oldp+269,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__T_Res));
        tracep->fullCData(oldp+270,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__XY_State),2);
        tracep->fullCData(oldp+271,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Pre_XY_F_M),3);
        tracep->fullBit(oldp+272,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__NextIs_XY_Fetch));
        tracep->fullBit(oldp+273,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__XY_Ind));
        tracep->fullBit(oldp+274,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__No_BTR));
        tracep->fullBit(oldp+275,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__BTR_r));
        tracep->fullBit(oldp+276,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Auto_Wait));
        tracep->fullBit(oldp+277,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Auto_Wait_t1));
        tracep->fullBit(oldp+278,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Auto_Wait_t2));
        tracep->fullBit(oldp+279,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__IncDecZ));
        tracep->fullCData(oldp+280,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__BusB),8);
        tracep->fullCData(oldp+281,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__BusA),8);
        tracep->fullCData(oldp+282,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ALU_Q),8);
        tracep->fullCData(oldp+283,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__F_Out),8);
        tracep->fullCData(oldp+284,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Read_To_Reg_r),5);
        tracep->fullBit(oldp+285,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Arith16_r));
        tracep->fullBit(oldp+286,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Z16_r));
        tracep->fullCData(oldp+287,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ALU_Op_r),4);
        tracep->fullBit(oldp+288,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Save_ALU_r));
        tracep->fullBit(oldp+289,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__PreserveC_r));
        tracep->fullCData(oldp+290,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__mcycles),3);
        tracep->fullCData(oldp+291,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__mcycles_d),3);
        tracep->fullCData(oldp+292,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__tstates),3);
        tracep->fullBit(oldp+293,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__IntCycle));
        tracep->fullBit(oldp+294,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__NMICycle));
        tracep->fullBit(oldp+295,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Inc_PC));
        tracep->fullBit(oldp+296,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Inc_WZ));
        tracep->fullCData(oldp+297,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__IncDec_16),4);
        tracep->fullCData(oldp+298,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Prefix),2);
        tracep->fullBit(oldp+299,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Read_To_Acc));
        tracep->fullBit(oldp+300,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Read_To_Reg));
        tracep->fullCData(oldp+301,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Set_BusB_To),4);
        tracep->fullCData(oldp+302,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Set_BusA_To),4);
        tracep->fullCData(oldp+303,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ALU_Op),4);
        tracep->fullBit(oldp+304,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Save_ALU));
        tracep->fullBit(oldp+305,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__PreserveC));
        tracep->fullBit(oldp+306,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Arith16));
        tracep->fullCData(oldp+307,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Set_Addr_To),3);
        tracep->fullBit(oldp+308,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Jump));
        tracep->fullBit(oldp+309,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__JumpE));
        tracep->fullBit(oldp+310,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__JumpXY));
        tracep->fullBit(oldp+311,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Call));
        tracep->fullBit(oldp+312,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__RstP));
        tracep->fullBit(oldp+313,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__LDZ));
        tracep->fullBit(oldp+314,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__LDW));
        tracep->fullBit(oldp+315,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__LDSPHL));
        tracep->fullBit(oldp+316,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__iorq_i));
        tracep->fullCData(oldp+317,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Special_LD),3);
        tracep->fullBit(oldp+318,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ExchangeDH));
        tracep->fullBit(oldp+319,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ExchangeRp));
        tracep->fullBit(oldp+320,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ExchangeAF));
        tracep->fullBit(oldp+321,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ExchangeRS));
        tracep->fullBit(oldp+322,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_DJNZ));
        tracep->fullBit(oldp+323,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_CPL));
        tracep->fullBit(oldp+324,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_CCF));
        tracep->fullBit(oldp+325,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_SCF));
        tracep->fullBit(oldp+326,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_RETN));
        tracep->fullBit(oldp+327,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_BT));
        tracep->fullBit(oldp+328,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_BC));
        tracep->fullBit(oldp+329,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_BTR));
        tracep->fullBit(oldp+330,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_RLD));
        tracep->fullBit(oldp+331,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_RRD));
        tracep->fullBit(oldp+332,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__I_INRC));
        tracep->fullBit(oldp+333,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__SetDI));
        tracep->fullBit(oldp+334,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__SetEI));
        tracep->fullCData(oldp+335,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__IMode),2);
        tracep->fullBit(oldp+336,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Halt));
        tracep->fullSData(oldp+337,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__PC16),16);
        tracep->fullSData(oldp+338,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__PC16_B),16);
        tracep->fullSData(oldp+339,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__SP16),16);
        tracep->fullSData(oldp+340,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__SP16_A),16);
        tracep->fullSData(oldp+341,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__SP16_B),16);
        tracep->fullSData(oldp+342,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__ID16_B),16);
        tracep->fullBit(oldp+343,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__Oldnmi_n));
        tracep->fullCData(oldp+344,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__IR),8);
        tracep->fullCData(oldp+345,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__ISet),2);
        tracep->fullCData(oldp+346,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycle),7);
        tracep->fullCData(oldp+347,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__F),8);
        tracep->fullBit(oldp+348,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__NMICycle));
        tracep->fullBit(oldp+349,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__IntCycle));
        tracep->fullCData(oldp+350,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__MCycles),3);
        tracep->fullCData(oldp+351,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__TStates),3);
        tracep->fullCData(oldp+352,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Prefix),2);
        tracep->fullBit(oldp+353,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_PC));
        tracep->fullBit(oldp+354,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Inc_WZ));
        tracep->fullCData(oldp+355,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__IncDec_16),4);
        tracep->fullBit(oldp+356,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Reg));
        tracep->fullBit(oldp+357,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Read_To_Acc));
        tracep->fullCData(oldp+358,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusA_To),4);
        tracep->fullCData(oldp+359,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_BusB_To),4);
        tracep->fullCData(oldp+360,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__ALU_Op),4);
        tracep->fullBit(oldp+361,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Save_ALU));
        tracep->fullBit(oldp+362,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__PreserveC));
        tracep->fullBit(oldp+363,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Arith16));
        tracep->fullCData(oldp+364,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Set_Addr_To),3);
        tracep->fullBit(oldp+365,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__IORQ));
        tracep->fullBit(oldp+366,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Jump));
        tracep->fullBit(oldp+367,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpE));
        tracep->fullBit(oldp+368,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__JumpXY));
        tracep->fullBit(oldp+369,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Call));
        tracep->fullBit(oldp+370,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__RstP));
        tracep->fullBit(oldp+371,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__LDZ));
        tracep->fullBit(oldp+372,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__LDW));
        tracep->fullBit(oldp+373,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__LDSPHL));
        tracep->fullCData(oldp+374,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Special_LD),3);
        tracep->fullBit(oldp+375,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeDH));
        tracep->fullBit(oldp+376,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRp));
        tracep->fullBit(oldp+377,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeAF));
        tracep->fullBit(oldp+378,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__ExchangeRS));
        tracep->fullBit(oldp+379,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_DJNZ));
        tracep->fullBit(oldp+380,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CPL));
        tracep->fullBit(oldp+381,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_CCF));
        tracep->fullBit(oldp+382,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_SCF));
        tracep->fullBit(oldp+383,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RETN));
        tracep->fullBit(oldp+384,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BT));
        tracep->fullBit(oldp+385,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BC));
        tracep->fullBit(oldp+386,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_BTR));
        tracep->fullBit(oldp+387,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RLD));
        tracep->fullBit(oldp+388,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_RRD));
        tracep->fullBit(oldp+389,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__I_INRC));
        tracep->fullBit(oldp+390,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__SetDI));
        tracep->fullBit(oldp+391,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__SetEI));
        tracep->fullCData(oldp+392,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__IMode),2);
        tracep->fullBit(oldp+393,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Halt));
        tracep->fullBit(oldp+394,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__NoRead));
        tracep->fullBit(oldp+395,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__Write));
        tracep->fullCData(oldp+396,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__DDD),3);
        tracep->fullCData(oldp+397,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__SSS),3);
        tracep->fullCData(oldp+398,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_mcode__DOT__DPAIR),2);
        tracep->fullBit(oldp+399,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__Arith16));
        tracep->fullBit(oldp+400,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__Z16));
        tracep->fullCData(oldp+401,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__ALU_Op),4);
        tracep->fullCData(oldp+402,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__IR),6);
        tracep->fullCData(oldp+403,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__ISet),2);
        tracep->fullCData(oldp+404,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__BusA),8);
        tracep->fullCData(oldp+405,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__BusB),8);
        tracep->fullCData(oldp+406,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__F_In),8);
        tracep->fullCData(oldp+407,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__Q),8);
        tracep->fullCData(oldp+408,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__F_Out),8);
        tracep->fullBit(oldp+409,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__UseCarry));
        tracep->fullBit(oldp+410,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__Carry7_v));
        tracep->fullBit(oldp+411,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__OverFlow_v));
        tracep->fullBit(oldp+412,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__HalfCarry_v));
        tracep->fullBit(oldp+413,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__Carry_v));
        tracep->fullCData(oldp+414,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__Q_v),8);
        tracep->fullCData(oldp+415,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__BitMask),8);
        tracep->fullCData(oldp+416,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__Q_t),8);
        tracep->fullSData(oldp+417,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_alu__DOT__DAA_Q),9);
        tracep->fullCData(oldp+418,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__AddrC),3);
        tracep->fullCData(oldp+419,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__DOBH),8);
        tracep->fullCData(oldp+420,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__AddrA),3);
        tracep->fullCData(oldp+421,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__AddrB),3);
        tracep->fullCData(oldp+422,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__DIH),8);
        tracep->fullCData(oldp+423,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__DOAL),8);
        tracep->fullCData(oldp+424,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__DOCL),8);
        tracep->fullCData(oldp+425,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__DIL),8);
        tracep->fullCData(oldp+426,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__DOBL),8);
        tracep->fullCData(oldp+427,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__DOCH),8);
        tracep->fullCData(oldp+428,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__DOAH),8);
        tracep->fullBit(oldp+429,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__clk));
        tracep->fullBit(oldp+430,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__CEN));
        tracep->fullBit(oldp+431,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__WEH));
        tracep->fullBit(oldp+432,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__WEL));
        tracep->fullBit(oldp+433,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__DIRSET));
        tracep->fullCData(oldp+434,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[0]),8);
        tracep->fullCData(oldp+435,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[1]),8);
        tracep->fullCData(oldp+436,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[2]),8);
        tracep->fullCData(oldp+437,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[3]),8);
        tracep->fullCData(oldp+438,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[4]),8);
        tracep->fullCData(oldp+439,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[5]),8);
        tracep->fullCData(oldp+440,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[6]),8);
        tracep->fullCData(oldp+441,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsH[7]),8);
        tracep->fullCData(oldp+442,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[0]),8);
        tracep->fullCData(oldp+443,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[1]),8);
        tracep->fullCData(oldp+444,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[2]),8);
        tracep->fullCData(oldp+445,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[3]),8);
        tracep->fullCData(oldp+446,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[4]),8);
        tracep->fullCData(oldp+447,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[5]),8);
        tracep->fullCData(oldp+448,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[6]),8);
        tracep->fullCData(oldp+449,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__RegsL[7]),8);
        tracep->fullCData(oldp+450,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__B),8);
        tracep->fullCData(oldp+451,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__C),8);
        tracep->fullCData(oldp+452,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__D),8);
        tracep->fullCData(oldp+453,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__E),8);
        tracep->fullCData(oldp+454,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__H),8);
        tracep->fullCData(oldp+455,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__L),8);
        tracep->fullSData(oldp+456,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__IX),16);
        tracep->fullSData(oldp+457,(vlTOPp->top__DOT__sharpx1__DOT__Cpu__DOT__Z80CPU__DOT__i_tv80_core__DOT__i_reg__DOT__IY),16);
        tracep->fullIData(oldp+458,(8U),32);
        tracep->fullIData(oldp+459,(0xdU),32);
        tracep->fullIData(oldp+460,(0x10U),32);
        tracep->fullIData(oldp+461,(0xcU),32);
        tracep->fullIData(oldp+462,(0U),32);
        tracep->fullIData(oldp+463,(1U),32);
        tracep->fullIData(oldp+464,(2U),32);
        tracep->fullIData(oldp+465,(3U),32);
        tracep->fullIData(oldp+466,(4U),32);
        tracep->fullIData(oldp+467,(5U),32);
        tracep->fullIData(oldp+468,(6U),32);
        tracep->fullIData(oldp+469,(7U),32);
        tracep->fullCData(oldp+470,(7U),3);
        tracep->fullCData(oldp+471,(0U),3);
        tracep->fullCData(oldp+472,(1U),3);
        tracep->fullCData(oldp+473,(2U),3);
        tracep->fullCData(oldp+474,(4U),3);
        tracep->fullCData(oldp+475,(5U),3);
        tracep->fullCData(oldp+476,(6U),3);
    }
}
